<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Error inside the Promise</title>
</head>
<body>
    <script type="text/javascript">
    	let userAuthorized = false;
    	function getUserById(id){
    		return new Promise((resolve,reject) =>{
    			if(userAuthorized){
    				throw new Error("User is not Authorized");
    			}
                  resolve({
    				id:id,
    				username: "admin"
    			});
    		});
    		  return new Promise((resolve,reject) =>{
    			
    		});
    	}
    	try{
    		getUserById(7)
    		.then(user => console.log(user.username))
    		.catch(error => console.log('Cought by .catch' + error ));
    	}catch(error){
    		console.log('Cought by try/catch {$error}' );
    	}
    </script>
</body>
</html>